### PR TITLE
Fixed video duration limit for certain boards

### PR DESCRIPTION
**Pull request by VelocityRa**

### CODE REVIEW

**Comment by VelocityRa** [comment]
I just did `grunt`, was I supposed to do `grunt patch` or `grunt minor`?
I don't quite understand how these work, would be nice if someone could explain.

**Comment by zixaphir** [comment]
Do not worry about versions. I'll handle grunt patch/minor/release/etc.

**Comment by VelocityRa** [comment]
Ah, alright.

**Comment by VelocityRa** [comment]
Is there a reason you don't merge?

**Comment by zixaphir** [comment]
Sorry, just hadn't gotten to it yet.

**Pull request merged**
